name: Run Stock Downloader

on:
  workflow_dispatch:  # Manual run
  schedule:
    - cron: '0 3 * * *'   # 9:00 AM local
    - cron: '30 3 * * *'  # 9:30 AM local
    - cron: '58 3 * * *'
    - cron: '0 4 * * *'   # 10:00 AM local
    - cron: '30 4 * * *'  # 10:30 AM local
    - cron: '0 5 * * *'   # 11:00 AM local
    - cron: '30 5 * * *'  # 11:30 AM local
    - cron: '0 6 * * *'   # 12:00 PM local
    - cron: '30 6 * * *'  # 12:30 PM local

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium pandas gspread oauth2client gspread-dataframe webdriver-manager openpyxl pytz

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Create creds file
        run: |
          echo "${{ secrets.GCREDS_JSON }}" | base64 -d > gcreds.json

      - name: Run supbaseConnection
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcreds.json
        run: python supbaseConnection.py


      - name: Run std stock script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcreds.json
        run: python downLoad_std_stock_report.py
        

      - name: Run inventory script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcreds.json
        run: python downLoad_inventory_report.py

      - name: Run Invoice_summary
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcreds.json
        run: python downLoad_Invoice_summary.py

      - name: Run order_relased
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcreds.json
        run: python downLoad_order_relased.py

      - name: Clean up creds
        run: rm gcreds.json
