name: Run Stock Downloader

on:
  workflow_dispatch:  # Manual run
  schedule:
    - cron: '0 6 * * *'  # Every day at 6 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium pandas gspread oauth2client gspread-dataframe webdriver-manager openpyxl

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Create creds file
        run: echo "${{ secrets.GCREDS_JSON }}" > gcreds.json

      - name: Run script
        run: python downLoad_inventory_report.py

      - name: Clean up creds
        run: rm gcreds.json
